/*
 * File: app/view/InitialView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyDiary.view.InitialView', {
    extend: 'Ext.Panel',
    alias: 'widget.mainview',

    requires: [
        'MyDiary.view.LoginPanel',
        'MyDiary.view.MainNotesListView',
        'MyDiary.view.RegistrationPanel',
        'Ext.Panel'
    ],

    config: {
        fullscreen: true,
        layout: 'card',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'loginpanel'
            },
            {
                xtype: 'mainnoteslistview'
            },
            {
                xtype: 'registrationpanel'
            }
        ]
    }

});