/*
 * File: app/view/MainNotesListView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyDiary.view.MainNotesListView', {
    extend: 'Ext.Panel',
    alias: 'widget.mainnoteslistview',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        cls: 'mainnotes-listview-cls',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'light',
                items: [
                    {
                        xtype: 'button',
                        scale: 'large',
                        cls: 'toolbar-button-cls',
                        ui: 'plain',
                        icon: 'resources/images/addnote.png'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        cls: 'toolbar-button-cls',
                        ui: 'plain',
                        icon: 'resources/images/more.png'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                ui: 'light',
                items: [
                    {
                        xtype: 'button',
                        centered: true,
                        cls: 'toolbar-button-cls',
                        ui: 'plain',
                        icon: 'resources/images/calendar.png'
                    }
                ]
            },
            {
                xtype: 'list',
                cls: 'listview-cls',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ]
    }

});